version: "{build}"

image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1

cache:
- packages -> **\packages.config

install:
- ps: >-
    $env:BUILD_VERSION = Select-String -Path Properties\AssemblyInfo.cs -Pattern 'AssemblyFileVersion\(\"(.*)\"\)' | %{ $_.Matches[0].Groups[1].Value }

    If ($env:APPVEYOR_REPO_TAG -eq $true) {
      $env:BUILD_VERSION = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")
    }

    $env:BUILD_VERSION_FILE = "$env:BUILD_VERSION.$env:APPVEYOR_BUILD_NUMBER"

    Update-AppveyorBuild -Version $env:BUILD_VERSION_FILE

    $version = $env:BUILD_VERSION -split '-'

    $env:BUILD_VERSION_FRIENDLY = $version[0] -replace "(\.0)$"

    If ($version[1]) {
      Update-AppveyorBuild -Version "$($version[0]).$env:APPVEYOR_BUILD_NUMBER-$($version[1])"

      $end = (Get-Culture).TextInfo.ToTitleCase($version[1].Replace("rc", "RC"))
      $env:BUILD_VERSION_FRIENDLY += " " + $end -replace "([a-z]+)(\d+)",'$1 $2'
    }

    $env:BUILD_VERSION_FRIENDLY += " Build $env:APPVEYOR_BUILD_NUMBER"

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: $(BUILD_VERSION)
  assembly_file_version: $(BUILD_VERSION_FILE)
  assembly_informational_version: $(BUILD_VERSION_FRIENDLY)

before_build:
- nuget restore

build:
  project: PluginManager.sln
  verbosity: minimal

artifacts:
- path: bin\Release\nfpm.exe

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: 11Aj9GejhzBxJlpQAwmcgJKINliGVNQ/mWTTFZCylmKiwglzys7hWxRZiRfT7INp
  on:
    APPVEYOR_REPO_TAG: true

for:
-
  branches:
    only:
      - master

  environment:
    BT_USER:
      secure: WeKwDVyYUZltHMzCsNlq5w==
    BT_KEY:
      secure: piTpGhOfvdvWqMnPTWkLyuX/b1lHDazzSWt37UbgqUHCAdfsEb+0exY7AUnYzT7Z

  deploy_script:
  - curl -s -w "\n" -T "bin\Release\nfpm.exe" -u"%BT_USER%:%BT_KEY%" "https://api.bintray.com/content/nfive/nfpm/nfpm/%BUILD_VERSION_FILE%/%BUILD_VERSION_FILE%/nfpm.exe?publish=1"
